### ISSUE TITLE
unable to install on Joomla 4.3.3.

### ISSUE THREAD

**Issue by davidascherG** [ceford/j4xdemos-admin-mod-topmenu#1]
"Unable to detect manifest file."

**Comment by ceford** [comment]
This module is obsolete. A customtop menu position was included in the atum template and you can move the Administrator to the top position, although it needs some work on the css. Also, see the Phoca extensions - you should find a forked and improved version.

**Comment by davidascherG** [comment]
thanks for your response. I was able to find the updated version for Joomla
4 in the Phoca stuff. I should have looked a little more carefully before
bothering you. Sorry about that. Maybe you should add a pointer to Phoca on
the GitHub repository? it might save you from having to respond to another
idiot or idiots like me in the future.

dave
